"""
LeetCode 精选 100 题（由 tools/import_leetcode.py 自动生成，勿手改）
数据源: LeetCode Problems JSON Dataset（2913 题）
"""

# 每项与 BankQuestion 字段对应（type 均为 coding）
LC_QUESTIONS = [
    {
        "id": "LC001",
        "type": "coding",
        "category": "Array",
        "question": "【LeetCode 1】Two Sum\n\nGiven an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.\nYou may assume that each input would have exactly one solution, and you may not use the same element twice.\nYou can return the answer in any order.\nExample 1:\nExample 2:\nExample 3:\nConstraints:",
        "tags": ["Array", "Hash Table"],
        "expected_points": ["Array", "Hash Table"],
        "difficulty": 2,
        "code": {"language": "python", "function_signature": "class Solution:\n    def twoSum(self, nums: List[int], target: int) -> List[int]:", "test_cases": [{"name": "用例1", "input_code": "sol = Solution()\nprint(sol.twoSum(nums=[2, 7, 11, 15], target=9))", "expected": "[0, 1]"}, {"name": "用例2", "input_code": "sol = Solution()\nprint(sol.twoSum(nums=[3, 2, 4], target=6))", "expected": "[1, 2]"}, {"name": "用例3", "input_code": "sol = Solution()\nprint(sol.twoSum(nums=[3, 3], target=6))", "expected": "[0, 1]"}]},
    },
    {
        "id": "LC002",
        "type": "coding",
        "category": "Linked List",
        "question": "【LeetCode 2】Add Two Numbers\n\nYou are given two non-empty linked lists representing two non-negative integers. The digits are stored in reverse order, and each of their nodes contains a single digit. Add the two numbers and return the sum as a linked list.\nYou may assume the two numbers do not contain any leading zero, except the number 0 itself.\nExample 1:\nExample 2:\nExample 3:\nConstraints:",
        "tags": ["Linked List", "Math", "Recursion"],
        "expected_points": ["Linked List", "Math", "Recursion"],
        "difficulty": 3,
        "code": {"language": "python", "function_signature": "# Definition for singly-linked list.\n# class ListNode:\n#     def __init__(self, val=0, next=None):\n#         self.val = val\n#         self.next = next\nclass Solution:\n    def addTwoNumbers(self, l1: Optional[ListNode], l2: Optional[ListNode]) -> Optional[ListNode]:", "test_cases": []},
    },
    {
        "id": "LC003",
        "type": "coding",
        "category": "Hash Table",
        "question": "【LeetCode 3】Longest Substring Without Repeating Characters\n\nGiven a string s, find the length of the longest substring without duplicate characters.\nExample 1:\nExample 2:\nExample 3:\nConstraints:",
        "tags": ["Hash Table", "String", "Sliding Window"],
        "expected_points": ["Hash Table", "String", "Sliding Window"],
        "difficulty": 3,
        "code": {"language": "python", "function_signature": "class Solution:\n    def lengthOfLongestSubstring(self, s: str) -> int:", "test_cases": [{"name": "用例1", "input_code": "sol = Solution()\nprint(sol.lengthOfLongestSubstring(s='abcabcbb'))", "expected": "3"}, {"name": "用例2", "input_code": "sol = Solution()\nprint(sol.lengthOfLongestSubstring(s='bbbbb'))", "expected": "1"}, {"name": "用例3", "input_code": "sol = Solution()\nprint(sol.lengthOfLongestSubstring(s='pwwkew'))", "expected": "3"}]},
    },
    {
        "id": "LC004",
        "type": "coding",
        "category": "Array",
        "question": "【LeetCode 4】Median of Two Sorted Arrays\n\nGiven two sorted arrays nums1 and nums2 of size m and n respectively, return the median of the two sorted arrays.\nThe overall run time complexity should be O(log (m+n)).\nExample 1:\nExample 2:\nConstraints:",
        "tags": ["Array", "Binary Search", "Divide and Conquer"],
        "expected_points": ["Array", "Binary Search", "Divide and Conquer"],
        "difficulty": 4,
        "code": {"language": "python", "function_signature": "class Solution:\n    def findMedianSortedArrays(self, nums1: List[int], nums2: List[int]) -> float:", "test_cases": [{"name": "用例1", "input_code": "sol = Solution()\nprint(sol.findMedianSortedArrays(nums1=[1, 3], nums2=[2]))", "expected": "2.0"}, {"name": "用例2", "input_code": "sol = Solution()\nprint(sol.findMedianSortedArrays(nums1=[1, 2], nums2=[3, 4]))", "expected": "2.5"}]},
    },
    {
        "id": "LC005",
        "type": "coding",
        "category": "Two Pointers",
        "question": "【LeetCode 5】Longest Palindromic Substring\n\nGiven a string s, return the longest palindromic substring in s.\nExample 1:\nExample 2:\nConstraints:",
        "tags": ["Two Pointers", "String", "Dynamic Programming"],
        "expected_points": ["Two Pointers", "String", "Dynamic Programming"],
        "difficulty": 3,
        "code": {"language": "python", "function_signature": "class Solution:\n    def longestPalindrome(self, s: str) -> str:", "test_cases": [{"name": "用例1", "input_code": "sol = Solution()\nprint(sol.longestPalindrome(s='babad'))", "expected": "bab"}, {"name": "用例2", "input_code": "sol = Solution()\nprint(sol.longestPalindrome(s='cbbd'))", "expected": "bb"}]},
    },
    {
        "id": "LC006",
        "type": "coding",
        "category": "String",
        "question": "【LeetCode 6】Zigzag Conversion\n\nThe string \"PAYPALISHIRING\" is written in a zigzag pattern on a given number of rows like this: (you may want to display this pattern in a fixed font for better legibility)\nAnd then read line by line: \"PAHNAPLSIIGYIR\"\nWrite the code that will take a string and make this conversion given a number of rows:\nExample 1:\nExample 2:\nExample 3:\nConstraints:",
        "tags": ["String"],
        "expected_points": ["String"],
        "difficulty": 3,
        "code": {"language": "python", "function_signature": "class Solution:\n    def convert(self, s: str, numRows: int) -> str:", "test_cases": []},
    },
    {
        "id": "LC007",
        "type": "coding",
        "category": "Math",
        "question": "【LeetCode 7】Reverse Integer\n\nGiven a signed 32-bit integer x, return x with its digits reversed. If reversing x causes the value to go outside the signed 32-bit integer range [-231, 231 - 1], then return 0.\nAssume the environment does not allow you to store 64-bit integers (signed or unsigned).\nExample 1:\nExample 2:\nExample 3:\nConstraints:",
        "tags": ["Math"],
        "expected_points": ["Math"],
        "difficulty": 3,
        "code": {"language": "python", "function_signature": "class Solution:\n    def reverse(self, x: int) -> int:", "test_cases": [{"name": "用例1", "input_code": "sol = Solution()\nprint(sol.reverse(x=123))", "expected": "321"}, {"name": "用例2", "input_code": "sol = Solution()\nprint(sol.reverse(x=-123))", "expected": "-321"}, {"name": "用例3", "input_code": "sol = Solution()\nprint(sol.reverse(x=120))", "expected": "21"}]},
    },
    {
        "id": "LC008",
        "type": "coding",
        "category": "String",
        "question": "【LeetCode 8】String to Integer (atoi)\n\nImplement the myAtoi(string s) function, which converts a string to a 32-bit signed integer.\nThe algorithm for myAtoi(string s) is as follows:\nReturn the integer as the final result.\nExample 1:\nExample 2:\nExample 3:\nExample 4:\nExample 5:\nConstraints:",
        "tags": ["String"],
        "expected_points": ["String"],
        "difficulty": 3,
        "code": {"language": "python", "function_signature": "class Solution:\n    def myAtoi(self, s: str) -> int:", "test_cases": []},
    },
    {
        "id": "LC009",
        "type": "coding",
        "category": "Math",
        "question": "【LeetCode 9】Palindrome Number\n\nGiven an integer x, return true if x is a palindrome, and false otherwise.\nExample 1:\nExample 2:\nExample 3:\nConstraints:",
        "tags": ["Math"],
        "expected_points": ["Math"],
        "difficulty": 2,
        "code": {"language": "python", "function_signature": "class Solution:\n    def isPalindrome(self, x: int) -> bool:", "test_cases": [{"name": "用例1", "input_code": "sol = Solution()\nprint(sol.isPalindrome(x=121))", "expected": "True"}, {"name": "用例2", "input_code": "sol = Solution()\nprint(sol.isPalindrome(x=-121))", "expected": "False"}, {"name": "用例3", "input_code": "sol = Solution()\nprint(sol.isPalindrome(x=10))", "expected": "False"}]},
    },
    {
        "id": "LC010",
        "type": "coding",
        "category": "String",
        "question": "【LeetCode 10】Regular Expression Matching\n\nGiven an input string s and a pattern p, implement regular expression matching with support for '.' and '*' where:\nThe matching should cover the entire input string (not partial).\nExample 1:\nExample 2:\nExample 3:\nConstraints:",
        "tags": ["String", "Dynamic Programming", "Recursion"],
        "expected_points": ["String", "Dynamic Programming", "Recursion"],
        "difficulty": 4,
        "code": {"language": "python", "function_signature": "class Solution:\n    def isMatch(self, s: str, p: str) -> bool:", "test_cases": [{"name": "用例1", "input_code": "sol = Solution()\nprint(sol.isMatch(s='aa', p='a'))", "expected": "False"}, {"name": "用例2", "input_code": "sol = Solution()\nprint(sol.isMatch(s='aa', p='a*'))", "expected": "True"}, {"name": "用例3", "input_code": "sol = Solution()\nprint(sol.isMatch(s='ab', p='.*'))", "expected": "True"}]},
    },
    {
        "id": "LC011",
        "type": "coding",
        "category": "Array",
        "question": "【LeetCode 11】Container With Most Water\n\nYou are given an integer array height of length n. There are n vertical lines drawn such that the two endpoints of the ith line are (i, 0) and (i, height[i]).\nFind two lines that together with the x-axis form a container, such that the container contains the most water.\nReturn the maximum amount of water a container can store.\nNotice that you may not slant the container.\nExample 1:\nExample 2:\nConstraints:",
        "tags": ["Array", "Two Pointers", "Greedy"],
        "expected_points": ["Array", "Two Pointers", "Greedy"],
        "difficulty": 3,
        "code": {"language": "python", "function_signature": "class Solution:\n    def maxArea(self, height: List[int]) -> int:", "test_cases": [{"name": "用例1", "input_code": "sol = Solution()\nprint(sol.maxArea(height=[1, 8, 6, 2, 5, 4, 8, 3, 7]))", "expected": "49"}, {"name": "用例2", "input_code": "sol = Solution()\nprint(sol.maxArea(height=[1, 1]))", "expected": "1"}]},
    },
    {
        "id": "LC012",
        "type": "coding",
        "category": "Hash Table",
        "question": "【LeetCode 12】Integer to Roman\n\nSeven different symbols represent Roman numerals with the following values:\nRoman numerals are formed by appending the conversions of decimal place values from highest to lowest. Converting a decimal place value into a Roman numeral has the following rules:\nGiven an integer, convert it to a Roman numeral.\nExample 1:\nExample 2:\nExample 3:\nConstraints:",
        "tags": ["Hash Table", "Math", "String"],
        "expected_points": ["Hash Table", "Math", "String"],
        "difficulty": 3,
        "code": {"language": "python", "function_signature": "class Solution:\n    def intToRoman(self, num: int) -> str:", "test_cases": []},
    },
    {
        "id": "LC013",
        "type": "coding",
        "category": "Hash Table",
        "question": "【LeetCode 13】Roman to Integer\n\nRoman numerals are represented by seven different symbols: I, V, X, L, C, D and M.\nFor example, 2 is written as II in Roman numeral, just two ones added together. 12 is written as XII, which is simply X + II. The number 27 is written as XXVII, which is XX + V + II.\nRoman numerals are usually written largest to smallest from left to right. However, the numeral for four is not IIII. Instead, the number four is written as IV. Because the one is before the five we subtract it making four. The same principle applies to the number nine, which is written as IX. There are six instances where subtracti",
        "tags": ["Hash Table", "Math", "String"],
        "expected_points": ["Hash Table", "Math", "String"],
        "difficulty": 2,
        "code": {"language": "python", "function_signature": "class Solution:\n    def romanToInt(self, s: str) -> int:", "test_cases": []},
    },
    {
        "id": "LC014",
        "type": "coding",
        "category": "Array",
        "question": "【LeetCode 14】Longest Common Prefix\n\nWrite a function to find the longest common prefix string amongst an array of strings.\nIf there is no common prefix, return an empty string \"\".\nExample 1:\nExample 2:\nConstraints:",
        "tags": ["Array", "String", "Trie"],
        "expected_points": ["Array", "String", "Trie"],
        "difficulty": 2,
        "code": {"language": "python", "function_signature": "class Solution:\n    def longestCommonPrefix(self, strs: List[str]) -> str:", "test_cases": [{"name": "用例1", "input_code": "sol = Solution()\nprint(sol.longestCommonPrefix(strs=['flower', 'flow', 'flight']))", "expected": "fl"}, {"name": "用例2", "input_code": "sol = Solution()\nprint(sol.longestCommonPrefix(strs=['dog', 'racecar', 'car']))", "expected": ""}]},
    },
    {
        "id": "LC015",
        "type": "coding",
        "category": "Array",
        "question": "【LeetCode 15】3Sum\n\nGiven an integer array nums, return all the triplets [nums[i], nums[j], nums[k]] such that i != j, i != k, and j != k, and nums[i] + nums[j] + nums[k] == 0.\nNotice that the solution set must not contain duplicate triplets.\nExample 1:\nExample 2:\nExample 3:\nConstraints:",
        "tags": ["Array", "Two Pointers", "Sorting"],
        "expected_points": ["Array", "Two Pointers", "Sorting"],
        "difficulty": 3,
        "code": {"language": "python", "function_signature": "class Solution:\n    def threeSum(self, nums: List[int]) -> List[List[int]]:", "test_cases": [{"name": "用例1", "input_code": "sol = Solution()\nprint(sol.threeSum(nums=[-1, 0, 1, 2, -1, -4]))", "expected": "[[-1, -1, 2], [-1, 0, 1]]"}, {"name": "用例2", "input_code": "sol = Solution()\nprint(sol.threeSum(nums=[0, 1, 1]))", "expected": "[]"}, {"name": "用例3", "input_code": "sol = Solution()\nprint(sol.threeSum(nums=[0, 0, 0]))", "expected": "[[0, 0, 0]]"}]},
    },
    {
        "id": "LC016",
        "type": "coding",
        "category": "Array",
        "question": "【LeetCode 16】3Sum Closest\n\nGiven an integer array nums of length n and an integer target, find three integers in nums such that the sum is closest to target.\nReturn the sum of the three integers.\nYou may assume that each input would have exactly one solution.\nExample 1:\nExample 2:\nConstraints:",
        "tags": ["Array", "Two Pointers", "Sorting"],
        "expected_points": ["Array", "Two Pointers", "Sorting"],
        "difficulty": 3,
        "code": {"language": "python", "function_signature": "class Solution:\n    def threeSumClosest(self, nums: List[int], target: int) -> int:", "test_cases": [{"name": "用例1", "input_code": "sol = Solution()\nprint(sol.threeSumClosest(nums=[-1, 2, 1, -4], target=1))", "expected": "2"}, {"name": "用例2", "input_code": "sol = Solution()\nprint(sol.threeSumClosest(nums=[0, 0, 0], target=1))", "expected": "0"}]},
    },
    {
        "id": "LC017",
        "type": "coding",
        "category": "Hash Table",
        "question": "【LeetCode 17】Letter Combinations of a Phone Number\n\nGiven a string containing digits from 2-9 inclusive, return all possible letter combinations that the number could represent. Return the answer in any order.\nA mapping of digits to letters (just like on the telephone buttons) is given below. Note that 1 does not map to any letters.\nExample 1:\nExample 2:\nExample 3:\nConstraints:",
        "tags": ["Hash Table", "String", "Backtracking"],
        "expected_points": ["Hash Table", "String", "Backtracking"],
        "difficulty": 3,
        "code": {"language": "python", "function_signature": "class Solution:\n    def letterCombinations(self, digits: str) -> List[str]:", "test_cases": [{"name": "用例1", "input_code": "sol = Solution()\nprint(sol.letterCombinations(digits='23'))", "expected": "['ad', 'ae', 'af', 'bd', 'be', 'bf', 'cd', 'ce', 'cf']"}, {"name": "用例2", "input_code": "sol = Solution()\nprint(sol.letterCombinations(digits=''))", "expected": "[]"}, {"name": "用例3", "input_code": "sol = Solution()\nprint(sol.letterCombinations(digits='2'))", "expected": "['a', 'b', 'c']"}]},
    },
    {
        "id": "LC019",
        "type": "coding",
        "category": "Linked List",
        "question": "【LeetCode 19】Remove Nth Node From End of List\n\nGiven the head of a linked list, remove the nth node from the end of the list and return its head.\nExample 1:\nExample 2:\nExample 3:\nConstraints:\nFollow up: Could you do this in one pass?",
        "tags": ["Linked List", "Two Pointers"],
        "expected_points": ["Linked List", "Two Pointers"],
        "difficulty": 3,
        "code": {"language": "python", "function_signature": "# Definition for singly-linked list.\n# class ListNode:\n#     def __init__(self, val=0, next=None):\n#         self.val = val\n#         self.next = next\nclass Solution:\n    def removeNthFromEnd(self, head: Optional[ListNode], n: int) -> Optional[ListNode]:", "test_cases": []},
    },
    {
        "id": "LC020",
        "type": "coding",
        "category": "String",
        "question": "【LeetCode 20】Valid Parentheses\n\nGiven a string s containing just the characters '(', ')', '{', '}', '[' and ']', determine if the input string is valid.\nAn input string is valid if:\nExample 1:\nExample 2:\nExample 3:\nExample 4:\nExample 5:\nConstraints:",
        "tags": ["String", "Stack"],
        "expected_points": ["String", "Stack"],
        "difficulty": 2,
        "code": {"language": "python", "function_signature": "class Solution:\n    def isValid(self, s: str) -> bool:", "test_cases": [{"name": "用例1", "input_code": "sol = Solution()\nprint(sol.isValid(s='()'))", "expected": "True"}, {"name": "用例2", "input_code": "sol = Solution()\nprint(sol.isValid(s='()[]{}'))", "expected": "True"}, {"name": "用例3", "input_code": "sol = Solution()\nprint(sol.isValid(s='(]'))", "expected": "False"}, {"name": "用例4", "input_code": "sol = Solution()\nprint(sol.isValid(s='([])'))", "expected": "True"}, {"name": "用例5", "input_code": "sol = Solution()\nprint(sol.isValid(s='([)]'))", "expected": "False"}]},
    },
    {
        "id": "LC021",
        "type": "coding",
        "category": "Linked List",
        "question": "【LeetCode 21】Merge Two Sorted Lists\n\nYou are given the heads of two sorted linked lists list1 and list2.\nMerge the two lists into one sorted list. The list should be made by splicing together the nodes of the first two lists.\nReturn the head of the merged linked list.\nExample 1:\nExample 2:\nExample 3:\nConstraints:",
        "tags": ["Linked List", "Recursion"],
        "expected_points": ["Linked List", "Recursion"],
        "difficulty": 2,
        "code": {"language": "python", "function_signature": "# Definition for singly-linked list.\n# class ListNode:\n#     def __init__(self, val=0, next=None):\n#         self.val = val\n#         self.next = next\nclass Solution:\n    def mergeTwoLists(self, list1: Optional[ListNode], list2: Optional[ListNode]) -> Optional[ListNode]:", "test_cases": []},
    },
    {
        "id": "LC022",
        "type": "coding",
        "category": "String",
        "question": "【LeetCode 22】Generate Parentheses\n\nGiven n pairs of parentheses, write a function to generate all combinations of well-formed parentheses.\nExample 1:\nExample 2:\nConstraints:",
        "tags": ["String", "Dynamic Programming", "Backtracking"],
        "expected_points": ["String", "Dynamic Programming", "Backtracking"],
        "difficulty": 3,
        "code": {"language": "python", "function_signature": "class Solution:\n    def generateParenthesis(self, n: int) -> List[str]:", "test_cases": [{"name": "用例1", "input_code": "sol = Solution()\nprint(sol.generateParenthesis(n=3))", "expected": "['((()))', '(()())', '(())()', '()(())', '()()()']"}, {"name": "用例2", "input_code": "sol = Solution()\nprint(sol.generateParenthesis(n=1))", "expected": "['()']"}]},
    },
    {
        "id": "LC023",
        "type": "coding",
        "category": "Linked List",
        "question": "【LeetCode 23】Merge k Sorted Lists\n\nYou are given an array of k linked-lists lists, each linked-list is sorted in ascending order.\nMerge all the linked-lists into one sorted linked-list and return it.\nExample 1:\nExample 2:\nExample 3:\nConstraints:",
        "tags": ["Linked List", "Divide and Conquer", "Heap (Priority Queue)", "Merge Sort"],
        "expected_points": ["Linked List", "Divide and Conquer", "Heap (Priority Queue)", "Merge Sort"],
        "difficulty": 4,
        "code": {"language": "python", "function_signature": "# Definition for singly-linked list.\n# class ListNode:\n#     def __init__(self, val=0, next=None):\n#         self.val = val\n#         self.next = next\nclass Solution:\n    def mergeKLists(self, lists: List[Optional[ListNode]]) -> Optional[ListNode]:", "test_cases": []},
    },
    {
        "id": "LC024",
        "type": "coding",
        "category": "Linked List",
        "question": "【LeetCode 24】Swap Nodes in Pairs\n\nGiven a linked list, swap every two adjacent nodes and return its head. You must solve the problem without modifying the values in the list's nodes (i.e., only nodes themselves may be changed.)\nExample 1:\nExample 2:\nExample 3:\nExample 4:\nConstraints:",
        "tags": ["Linked List", "Recursion"],
        "expected_points": ["Linked List", "Recursion"],
        "difficulty": 3,
        "code": {"language": "python", "function_signature": "# Definition for singly-linked list.\n# class ListNode:\n#     def __init__(self, val=0, next=None):\n#         self.val = val\n#         self.next = next\nclass Solution:\n    def swapPairs(self, head: Optional[ListNode]) -> Optional[ListNode]:", "test_cases": []},
    },
    {
        "id": "LC025",
        "type": "coding",
        "category": "Linked List",
        "question": "【LeetCode 25】Reverse Nodes in k-Group\n\nGiven the head of a linked list, reverse the nodes of the list k at a time, and return the modified list.\nk is a positive integer and is less than or equal to the length of the linked list. If the number of nodes is not a multiple of k then left-out nodes, in the end, should remain as it is.\nYou may not alter the values in the list's nodes, only nodes themselves may be changed.\nExample 1:\nExample 2:\nConstraints:\nFollow-up: Can you solve the problem in O(1) extra memory space?",
        "tags": ["Linked List", "Recursion"],
        "expected_points": ["Linked List", "Recursion"],
        "difficulty": 4,
        "code": {"language": "python", "function_signature": "# Definition for singly-linked list.\n# class ListNode:\n#     def __init__(self, val=0, next=None):\n#         self.val = val\n#         self.next = next\nclass Solution:\n    def reverseKGroup(self, head: Optional[ListNode], k: int) -> Optional[ListNode]:", "test_cases": []},
    },
    {
        "id": "LC028",
        "type": "coding",
        "category": "Two Pointers",
        "question": "【LeetCode 28】Find the Index of the First Occurrence in a String\n\nGiven two strings needle and haystack, return the index of the first occurrence of needle in haystack, or -1 if needle is not part of haystack.\nExample 1:\nExample 2:\nConstraints:",
        "tags": ["Two Pointers", "String", "String Matching"],
        "expected_points": ["Two Pointers", "String", "String Matching"],
        "difficulty": 2,
        "code": {"language": "python", "function_signature": "class Solution:\n    def strStr(self, haystack: str, needle: str) -> int:", "test_cases": [{"name": "用例1", "input_code": "sol = Solution()\nprint(sol.strStr(haystack='sadbutsad', needle='sad'))", "expected": "0"}, {"name": "用例2", "input_code": "sol = Solution()\nprint(sol.strStr(haystack='leetcode', needle='leeto'))", "expected": "-1"}]},
    },
    {
        "id": "LC029",
        "type": "coding",
        "category": "Math",
        "question": "【LeetCode 29】Divide Two Integers\n\nGiven two integers dividend and divisor, divide two integers without using multiplication, division, and mod operator.\nThe integer division should truncate toward zero, which means losing its fractional part. For example, 8.345 would be truncated to 8, and -2.7335 would be truncated to -2.\nReturn the quotient after dividing dividend by divisor.\nNote: Assume we are dealing with an environment that could only store integers within the 32-bit signed integer range: [−231, 231 − 1]. For this problem, if the quotient is strictly greater than 231 - 1, then return 231 - 1, and if the quotient is stric",
        "tags": ["Math", "Bit Manipulation"],
        "expected_points": ["Math", "Bit Manipulation"],
        "difficulty": 3,
        "code": {"language": "python", "function_signature": "class Solution:\n    def divide(self, dividend: int, divisor: int) -> int:", "test_cases": [{"name": "用例1", "input_code": "sol = Solution()\nprint(sol.divide(dividend=10, divisor=3))", "expected": "3"}, {"name": "用例2", "input_code": "sol = Solution()\nprint(sol.divide(dividend=7, divisor=-3))", "expected": "-2"}]},
    },
    {
        "id": "LC030",
        "type": "coding",
        "category": "Hash Table",
        "question": "【LeetCode 30】Substring with Concatenation of All Words\n\nYou are given a string s and an array of strings words. All the strings of words are of the same length.\nA concatenated string is a string that exactly contains all the strings of any permutation of words concatenated.\nReturn an array of the starting indices of all the concatenated substrings in s. You can return the answer in any order.\nExample 1:\nExample 2:\nExample 3:\nConstraints:",
        "tags": ["Hash Table", "String", "Sliding Window"],
        "expected_points": ["Hash Table", "String", "Sliding Window"],
        "difficulty": 4,
        "code": {"language": "python", "function_signature": "class Solution:\n    def findSubstring(self, s: str, words: List[str]) -> List[int]:", "test_cases": [{"name": "用例1", "input_code": "sol = Solution()\nprint(sol.findSubstring(s='barfoothefoobarman', words=['foo', 'bar']))", "expected": "[0, 9]"}, {"name": "用例2", "input_code": "sol = Solution()\nprint(sol.findSubstring(s='wordgoodgoodgoodbestword', words=['word', 'good', 'best', 'word']))", "expected": "[]"}, {"name": "用例3", "input_code": "sol = Solution()\nprint(sol.findSubstring(s='barfoofoobarthefoobarman', words=['bar', 'foo', 'the']))", "expected": "[6, 9, 12]"}]},
    },
    {
        "id": "LC032",
        "type": "coding",
        "category": "String",
        "question": "【LeetCode 32】Longest Valid Parentheses\n\nGiven a string containing just the characters '(' and ')', return the length of the longest valid (well-formed) parentheses substring.\nExample 1:\nExample 2:\nExample 3:\nConstraints:",
        "tags": ["String", "Dynamic Programming", "Stack"],
        "expected_points": ["String", "Dynamic Programming", "Stack"],
        "difficulty": 4,
        "code": {"language": "python", "function_signature": "class Solution:\n    def longestValidParentheses(self, s: str) -> int:", "test_cases": [{"name": "用例1", "input_code": "sol = Solution()\nprint(sol.longestValidParentheses(s='(()'))", "expected": "2"}, {"name": "用例2", "input_code": "sol = Solution()\nprint(sol.longestValidParentheses(s=')()())'))", "expected": "4"}, {"name": "用例3", "input_code": "sol = Solution()\nprint(sol.longestValidParentheses(s=''))", "expected": "0"}]},
    },
    {
        "id": "LC043",
        "type": "coding",
        "category": "Math",
        "question": "【LeetCode 43】Multiply Strings\n\nGiven two non-negative integers num1 and num2 represented as strings, return the product of num1 and num2, also represented as a string.\nNote: You must not use any built-in BigInteger library or convert the inputs to integer directly.\nExample 1:\nExample 2:\nConstraints:",
        "tags": ["Math", "String", "Simulation"],
        "expected_points": ["Math", "String", "Simulation"],
        "difficulty": 3,
        "code": {"language": "python", "function_signature": "class Solution:\n    def multiply(self, num1: str, num2: str) -> str:", "test_cases": [{"name": "用例1", "input_code": "sol = Solution()\nprint(sol.multiply(num1='2', num2='3'))", "expected": "6"}, {"name": "用例2", "input_code": "sol = Solution()\nprint(sol.multiply(num1='123', num2='456'))", "expected": "56088"}]},
    },
    {
        "id": "LC050",
        "type": "coding",
        "category": "Math",
        "question": "【LeetCode 50】Pow(x, n)\n\nImplement pow(x, n), which calculates x raised to the power n (i.e., xn).\nExample 1:\nExample 2:\nExample 3:\nConstraints:",
        "tags": ["Math", "Recursion"],
        "expected_points": ["Math", "Recursion"],
        "difficulty": 3,
        "code": {"language": "python", "function_signature": "class Solution:\n    def myPow(self, x: float, n: int) -> float:", "test_cases": [{"name": "用例1", "input_code": "sol = Solution()\nprint(sol.myPow(x=2.0, n=10))", "expected": "1024.0"}, {"name": "用例2", "input_code": "sol = Solution()\nprint(sol.myPow(x=2.1, n=3))", "expected": "9.261"}, {"name": "用例3", "input_code": "sol = Solution()\nprint(sol.myPow(x=2.0, n=-2))", "expected": "0.25"}]},
    },
    {
        "id": "LC052",
        "type": "coding",
        "category": "Backtracking",
        "question": "【LeetCode 52】N-Queens II\n\nThe n-queens puzzle is the problem of placing n queens on an n x n chessboard such that no two queens attack each other.\nGiven an integer n, return the number of distinct solutions to the n-queens puzzle.\nExample 1:\nExample 2:\nConstraints:",
        "tags": ["Backtracking"],
        "expected_points": ["Backtracking"],
        "difficulty": 4,
        "code": {"language": "python", "function_signature": "class Solution:\n    def totalNQueens(self, n: int) -> int:", "test_cases": [{"name": "用例1", "input_code": "sol = Solution()\nprint(sol.totalNQueens(n=4))", "expected": "2"}, {"name": "用例2", "input_code": "sol = Solution()\nprint(sol.totalNQueens(n=1))", "expected": "1"}]},
    },
    {
        "id": "LC060",
        "type": "coding",
        "category": "Math",
        "question": "【LeetCode 60】Permutation Sequence\n\nThe set [1, 2, 3, ..., n] contains a total of n! unique permutations.\nBy listing and labeling all of the permutations in order, we get the following sequence for n = 3:\nGiven n and k, return the kth permutation sequence.\nExample 1:\nExample 2:\nExample 3:\nConstraints:",
        "tags": ["Math", "Recursion"],
        "expected_points": ["Math", "Recursion"],
        "difficulty": 4,
        "code": {"language": "python", "function_signature": "class Solution:\n    def getPermutation(self, n: int, k: int) -> str:", "test_cases": [{"name": "用例1", "input_code": "sol = Solution()\nprint(sol.getPermutation(n=3, k=3))", "expected": "213"}, {"name": "用例2", "input_code": "sol = Solution()\nprint(sol.getPermutation(n=4, k=9))", "expected": "2314"}, {"name": "用例3", "input_code": "sol = Solution()\nprint(sol.getPermutation(n=3, k=1))", "expected": "123"}]},
    },
    {
        "id": "LC076",
        "type": "coding",
        "category": "Hash Table",
        "question": "【LeetCode 76】Minimum Window Substring\n\nGiven two strings s and t of lengths m and n respectively, return the minimum window substring of s such that every character in t (including duplicates) is included in the window. If there is no such substring, return the empty string \"\".\nThe testcases will be generated such that the answer is unique.\nExample 1:\nExample 2:\nExample 3:\nConstraints:\nFollow up: Could you find an algorithm that runs in O(m + n) time?",
        "tags": ["Hash Table", "String", "Sliding Window"],
        "expected_points": ["Hash Table", "String", "Sliding Window"],
        "difficulty": 4,
        "code": {"language": "python", "function_signature": "class Solution:\n    def minWindow(self, s: str, t: str) -> str:", "test_cases": [{"name": "用例1", "input_code": "sol = Solution()\nprint(sol.minWindow(s='ADOBECODEBANC', t='ABC'))", "expected": "BANC"}, {"name": "用例2", "input_code": "sol = Solution()\nprint(sol.minWindow(s='a', t='a'))", "expected": "a"}, {"name": "用例3", "input_code": "sol = Solution()\nprint(sol.minWindow(s='a', t='aa'))", "expected": ""}]},
    },
    {
        "id": "LC077",
        "type": "coding",
        "category": "Backtracking",
        "question": "【LeetCode 77】Combinations\n\nGiven two integers n and k, return all possible combinations of k numbers chosen from the range [1, n].\nYou may return the answer in any order.\nExample 1:\nExample 2:\nConstraints:",
        "tags": ["Backtracking"],
        "expected_points": ["Backtracking"],
        "difficulty": 3,
        "code": {"language": "python", "function_signature": "class Solution:\n    def combine(self, n: int, k: int) -> List[List[int]]:", "test_cases": [{"name": "用例1", "input_code": "sol = Solution()\nprint(sol.combine(n=4, k=2))", "expected": "[[1, 2], [1, 3], [1, 4], [2, 3], [2, 4], [3, 4]]"}, {"name": "用例2", "input_code": "sol = Solution()\nprint(sol.combine(n=1, k=1))", "expected": "[[1]]"}]},
    },
    {
        "id": "LC094",
        "type": "coding",
        "category": "Stack",
        "question": "【LeetCode 94】Binary Tree Inorder Traversal\n\nGiven the root of a binary tree, return the inorder traversal of its nodes' values.\nExample 1:\nExample 2:\nExample 3:\nExample 4:\nConstraints:",
        "tags": ["Stack", "Tree", "Depth-First Search", "Binary Tree"],
        "expected_points": ["Stack", "Tree", "Depth-First Search", "Binary Tree"],
        "difficulty": 2,
        "code": {"language": "python", "function_signature": "# Definition for a binary tree node.\n# class TreeNode:\n#     def __init__(self, val=0, left=None, right=None):\n#         self.val = val\n#         self.left = left\n#         self.right = right\nclass Solution:\n    def inorderTraversal(self, root: Optional[TreeNode]) -> List[int]:", "test_cases": []},
    },
    {
        "id": "LC095",
        "type": "coding",
        "category": "Dynamic Programming",
        "question": "【LeetCode 95】Unique Binary Search Trees II\n\nGiven an integer n, return all the structurally unique BST's (binary search trees), which has exactly n nodes of unique values from 1 to n. Return the answer in any order.\nExample 1:\nExample 2:\nConstraints:",
        "tags": ["Dynamic Programming", "Backtracking", "Tree", "Binary Search Tree", "Binary Tree"],
        "expected_points": ["Dynamic Programming", "Backtracking", "Tree", "Binary Search Tree", "Binary Tree"],
        "difficulty": 3,
        "code": {"language": "python", "function_signature": "# Definition for a binary tree node.\n# class TreeNode:\n#     def __init__(self, val=0, left=None, right=None):\n#         self.val = val\n#         self.left = left\n#         self.right = right\nclass Solution:\n    def generateTrees(self, n: int) -> List[Optional[TreeNode]]:", "test_cases": []},
    },
    {
        "id": "LC098",
        "type": "coding",
        "category": "Tree",
        "question": "【LeetCode 98】Validate Binary Search Tree\n\nGiven the root of a binary tree, determine if it is a valid binary search tree (BST).\nA valid BST is defined as follows:\nExample 1:\nExample 2:\nConstraints:",
        "tags": ["Tree", "Depth-First Search", "Binary Search Tree", "Binary Tree"],
        "expected_points": ["Tree", "Depth-First Search", "Binary Search Tree", "Binary Tree"],
        "difficulty": 3,
        "code": {"language": "python", "function_signature": "# Definition for a binary tree node.\n# class TreeNode:\n#     def __init__(self, val=0, left=None, right=None):\n#         self.val = val\n#         self.left = left\n#         self.right = right\nclass Solution:\n    def isValidBST(self, root: Optional[TreeNode]) -> bool:", "test_cases": []},
    },
    {
        "id": "LC099",
        "type": "coding",
        "category": "Tree",
        "question": "【LeetCode 99】Recover Binary Search Tree\n\nYou are given the root of a binary search tree (BST), where the values of exactly two nodes of the tree were swapped by mistake. Recover the tree without changing its structure.\nExample 1:\nExample 2:\nConstraints:",
        "tags": ["Tree", "Depth-First Search", "Binary Search Tree", "Binary Tree"],
        "expected_points": ["Tree", "Depth-First Search", "Binary Search Tree", "Binary Tree"],
        "difficulty": 3,
        "code": {"language": "python", "function_signature": "# Definition for a binary tree node.\n# class TreeNode:\n#     def __init__(self, val=0, left=None, right=None):\n#         self.val = val\n#         self.left = left\n#         self.right = right\nclass Solution:\n    def recoverTree(self, root: Optional[TreeNode]) -> None:\n        \"\"\"\n        Do not return anything, modify root in-place instead.\n        \"\"\"", "test_cases": []},
    },
    {
        "id": "LC100",
        "type": "coding",
        "category": "Tree",
        "question": "【LeetCode 100】Same Tree\n\nGiven the roots of two binary trees p and q, write a function to check if they are the same or not.\nTwo binary trees are considered the same if they are structurally identical, and the nodes have the same value.\nExample 1:\nExample 2:\nExample 3:\nConstraints:",
        "tags": ["Tree", "Depth-First Search", "Breadth-First Search", "Binary Tree"],
        "expected_points": ["Tree", "Depth-First Search", "Breadth-First Search", "Binary Tree"],
        "difficulty": 2,
        "code": {"language": "python", "function_signature": "# Definition for a binary tree node.\n# class TreeNode:\n#     def __init__(self, val=0, left=None, right=None):\n#         self.val = val\n#         self.left = left\n#         self.right = right\nclass Solution:\n    def isSameTree(self, p: Optional[TreeNode], q: Optional[TreeNode]) -> bool:", "test_cases": []},
    },
    {
        "id": "LC101",
        "type": "coding",
        "category": "Tree",
        "question": "【LeetCode 101】Symmetric Tree\n\nGiven the root of a binary tree, check whether it is a mirror of itself (i.e., symmetric around its center).\nExample 1:\nExample 2:\nConstraints:",
        "tags": ["Tree", "Depth-First Search", "Breadth-First Search", "Binary Tree"],
        "expected_points": ["Tree", "Depth-First Search", "Breadth-First Search", "Binary Tree"],
        "difficulty": 2,
        "code": {"language": "python", "function_signature": "# Definition for a binary tree node.\n# class TreeNode:\n#     def __init__(self, val=0, left=None, right=None):\n#         self.val = val\n#         self.left = left\n#         self.right = right\nclass Solution:\n    def isSymmetric(self, root: Optional[TreeNode]) -> bool:", "test_cases": []},
    },
    {
        "id": "LC102",
        "type": "coding",
        "category": "Tree",
        "question": "【LeetCode 102】Binary Tree Level Order Traversal\n\nGiven the root of a binary tree, return the level order traversal of its nodes' values. (i.e., from left to right, level by level).\nExample 1:\nExample 2:\nExample 3:\nConstraints:",
        "tags": ["Tree", "Breadth-First Search", "Binary Tree"],
        "expected_points": ["Tree", "Breadth-First Search", "Binary Tree"],
        "difficulty": 3,
        "code": {"language": "python", "function_signature": "# Definition for a binary tree node.\n# class TreeNode:\n#     def __init__(self, val=0, left=None, right=None):\n#         self.val = val\n#         self.left = left\n#         self.right = right\nclass Solution:\n    def levelOrder(self, root: Optional[TreeNode]) -> List[List[int]]:", "test_cases": []},
    },
    {
        "id": "LC103",
        "type": "coding",
        "category": "Tree",
        "question": "【LeetCode 103】Binary Tree Zigzag Level Order Traversal\n\nGiven the root of a binary tree, return the zigzag level order traversal of its nodes' values. (i.e., from left to right, then right to left for the next level and alternate between).\nExample 1:\nExample 2:\nExample 3:\nConstraints:",
        "tags": ["Tree", "Breadth-First Search", "Binary Tree"],
        "expected_points": ["Tree", "Breadth-First Search", "Binary Tree"],
        "difficulty": 3,
        "code": {"language": "python", "function_signature": "# Definition for a binary tree node.\n# class TreeNode:\n#     def __init__(self, val=0, left=None, right=None):\n#         self.val = val\n#         self.left = left\n#         self.right = right\nclass Solution:\n    def zigzagLevelOrder(self, root: Optional[TreeNode]) -> List[List[int]]:", "test_cases": []},
    },
    {
        "id": "LC113",
        "type": "coding",
        "category": "Backtracking",
        "question": "【LeetCode 113】Path Sum II\n\nGiven the root of a binary tree and an integer targetSum, return all root-to-leaf paths where the sum of the node values in the path equals targetSum. Each path should be returned as a list of the node values, not node references.\nA root-to-leaf path is a path starting from the root and ending at any leaf node. A leaf is a node with no children.\nExample 1:\nExample 2:\nExample 3:\nConstraints:",
        "tags": ["Backtracking", "Tree", "Depth-First Search", "Binary Tree"],
        "expected_points": ["Backtracking", "Tree", "Depth-First Search", "Binary Tree"],
        "difficulty": 3,
        "code": {"language": "python", "function_signature": "# Definition for a binary tree node.\n# class TreeNode:\n#     def __init__(self, val=0, left=None, right=None):\n#         self.val = val\n#         self.left = left\n#         self.right = right\nclass Solution:\n    def pathSum(self, root: Optional[TreeNode], targetSum: int) -> List[List[int]]:", "test_cases": []},
    },
    {
        "id": "LC124",
        "type": "coding",
        "category": "Dynamic Programming",
        "question": "【LeetCode 124】Binary Tree Maximum Path Sum\n\nA path in a binary tree is a sequence of nodes where each pair of adjacent nodes in the sequence has an edge connecting them. A node can only appear in the sequence at most once. Note that the path does not need to pass through the root.\nThe path sum of a path is the sum of the node's values in the path.\nGiven the root of a binary tree, return the maximum path sum of any non-empty path.\nExample 1:\nExample 2:\nConstraints:",
        "tags": ["Dynamic Programming", "Tree", "Depth-First Search", "Binary Tree"],
        "expected_points": ["Dynamic Programming", "Tree", "Depth-First Search", "Binary Tree"],
        "difficulty": 4,
        "code": {"language": "python", "function_signature": "# Definition for a binary tree node.\n# class TreeNode:\n#     def __init__(self, val=0, left=None, right=None):\n#         self.val = val\n#         self.left = left\n#         self.right = right\nclass Solution:\n    def maxPathSum(self, root: Optional[TreeNode]) -> int:", "test_cases": []},
    },
    {
        "id": "LC125",
        "type": "coding",
        "category": "Two Pointers",
        "question": "【LeetCode 125】Valid Palindrome\n\nA phrase is a palindrome if, after converting all uppercase letters into lowercase letters and removing all non-alphanumeric characters, it reads the same forward and backward. Alphanumeric characters include letters and numbers.\nGiven a string s, return true if it is a palindrome, or false otherwise.\nExample 1:\nExample 2:\nExample 3:\nConstraints:",
        "tags": ["Two Pointers", "String"],
        "expected_points": ["Two Pointers", "String"],
        "difficulty": 2,
        "code": {"language": "python", "function_signature": "class Solution:\n    def isPalindrome(self, s: str) -> bool:", "test_cases": [{"name": "用例1", "input_code": "sol = Solution()\nprint(sol.isPalindrome(s='A man, a plan, a canal: Panama'))", "expected": "True"}, {"name": "用例2", "input_code": "sol = Solution()\nprint(sol.isPalindrome(s='race a car'))", "expected": "False"}, {"name": "用例3", "input_code": "sol = Solution()\nprint(sol.isPalindrome(s=' '))", "expected": "True"}]},
    },
    {
        "id": "LC144",
        "type": "coding",
        "category": "Stack",
        "question": "【LeetCode 144】Binary Tree Preorder Traversal\n\nGiven the root of a binary tree, return the preorder traversal of its nodes' values.\nExample 1:\nExample 2:\nExample 3:\nExample 4:\nConstraints:\nFollow up: Recursive solution is trivial, could you do it iteratively?",
        "tags": ["Stack", "Tree", "Depth-First Search", "Binary Tree"],
        "expected_points": ["Stack", "Tree", "Depth-First Search", "Binary Tree"],
        "difficulty": 2,
        "code": {"language": "python", "function_signature": "# Definition for a binary tree node.\n# class TreeNode:\n#     def __init__(self, val=0, left=None, right=None):\n#         self.val = val\n#         self.left = left\n#         self.right = right\nclass Solution:\n    def preorderTraversal(self, root: Optional[TreeNode]) -> List[int]:", "test_cases": []},
    },
    {
        "id": "LC145",
        "type": "coding",
        "category": "Stack",
        "question": "【LeetCode 145】Binary Tree Postorder Traversal\n\nGiven the root of a binary tree, return the postorder traversal of its nodes' values.\nExample 1:\nExample 2:\nExample 3:\nExample 4:\nConstraints:",
        "tags": ["Stack", "Tree", "Depth-First Search", "Binary Tree"],
        "expected_points": ["Stack", "Tree", "Depth-First Search", "Binary Tree"],
        "difficulty": 2,
        "code": {"language": "python", "function_signature": "# Definition for a binary tree node.\n# class TreeNode:\n#     def __init__(self, val=0, left=None, right=None):\n#         self.val = val\n#         self.left = left\n#         self.right = right\nclass Solution:\n    def postorderTraversal(self, root: Optional[TreeNode]) -> List[int]:", "test_cases": []},
    },
    {
        "id": "LC151",
        "type": "coding",
        "category": "Two Pointers",
        "question": "【LeetCode 151】Reverse Words in a String\n\nGiven an input string s, reverse the order of the words.\nA word is defined as a sequence of non-space characters. The words in s will be separated by at least one space.\nReturn a string of the words in reverse order concatenated by a single space.\nNote that s may contain leading or trailing spaces or multiple spaces between two words. The returned string should only have a single space separating the words. Do not include any extra spaces.\nExample 1:\nExample 2:\nExample 3:\nConstraints:\nFollow-up: If the string data type is mutable in your language, can you solve it in-place with O(1) extra spac",
        "tags": ["Two Pointers", "String"],
        "expected_points": ["Two Pointers", "String"],
        "difficulty": 3,
        "code": {"language": "python", "function_signature": "class Solution:\n    def reverseWords(self, s: str) -> str:", "test_cases": [{"name": "用例1", "input_code": "sol = Solution()\nprint(sol.reverseWords(s='the sky is blue'))", "expected": "blue is sky the"}, {"name": "用例2", "input_code": "sol = Solution()\nprint(sol.reverseWords(s='  hello world  '))", "expected": "world hello"}, {"name": "用例3", "input_code": "sol = Solution()\nprint(sol.reverseWords(s='a good   example'))", "expected": "example good a"}]},
    },
    {
        "id": "LC155",
        "type": "coding",
        "category": "Stack",
        "question": "【LeetCode 155】Min Stack\n\nDesign a stack that supports push, pop, top, and retrieving the minimum element in constant time.\nImplement the MinStack class:\nYou must implement a solution with O(1) time complexity for each function.\nExample 1:\nConstraints:",
        "tags": ["Stack", "Design"],
        "expected_points": ["Stack", "Design"],
        "difficulty": 3,
        "code": {"language": "python", "function_signature": "class MinStack:\n\n    def __init__(self):\n        \n\n    def push(self, val: int) -> None:\n        \n\n    def pop(self) -> None:\n        \n\n    def top(self) -> int:\n        \n\n    def getMin(self) -> int:\n        \n\n\n# Your MinStack object will be instantiated and called as such:\n# obj = MinStack()\n# obj.push(val)\n# obj.pop()\n# param_3 = obj.top()\n# param_4 = obj.getMin()", "test_cases": []},
    },
    {
        "id": "LC165",
        "type": "coding",
        "category": "Two Pointers",
        "question": "【LeetCode 165】Compare Version Numbers\n\nGiven two version strings, version1 and version2, compare them. A version string consists of revisions separated by dots '.'. The value of the revision is its integer conversion ignoring leading zeros.\nTo compare version strings, compare their revision values in left-to-right order. If one of the version strings has fewer revisions, treat the missing revision values as 0.\nReturn the following:\nExample 1:\nExample 2:\nExample 3:\nConstraints:",
        "tags": ["Two Pointers", "String"],
        "expected_points": ["Two Pointers", "String"],
        "difficulty": 3,
        "code": {"language": "python", "function_signature": "class Solution:\n    def compareVersion(self, version1: str, version2: str) -> int:", "test_cases": [{"name": "用例1", "input_code": "sol = Solution()\nprint(sol.compareVersion(version1='1.2', version2='1.10'))", "expected": "-1"}, {"name": "用例2", "input_code": "sol = Solution()\nprint(sol.compareVersion(version1='1.01', version2='1.001'))", "expected": "0"}, {"name": "用例3", "input_code": "sol = Solution()\nprint(sol.compareVersion(version1='1.0', version2='1.0.0.0'))", "expected": "0"}]},
    },
    {
        "id": "LC173",
        "type": "coding",
        "category": "Stack",
        "question": "【LeetCode 173】Binary Search Tree Iterator\n\nImplement the BSTIterator class that represents an iterator over the in-order traversal of a binary search tree (BST):\nNotice that by initializing the pointer to a non-existent smallest number, the first call to next() will return the smallest element in the BST.\nYou may assume that next() calls will always be valid. That is, there will be at least a next number in the in-order traversal when next() is called.\nExample 1:\nConstraints:\nFollow up:",
        "tags": ["Stack", "Tree", "Design", "Binary Search Tree", "Binary Tree", "Iterator"],
        "expected_points": ["Stack", "Tree", "Design", "Binary Search Tree", "Binary Tree", "Iterator"],
        "difficulty": 3,
        "code": {"language": "python", "function_signature": "# Definition for a binary tree node.\n# class TreeNode:\n#     def __init__(self, val=0, left=None, right=None):\n#         self.val = val\n#         self.left = left\n#         self.right = right\nclass BSTIterator:\n\n    def __init__(self, root: Optional[TreeNode]):\n        \n\n    def next(self) -> int:\n        \n\n    def hasNext(self) -> bool:\n        \n\n\n# Your BSTIterator object will be instantiated and called as such:\n# obj = BSTIterator(root)\n# param_1 = obj.next()\n# param_2 = obj.hasNext()", "test_cases": []},
    },
    {
        "id": "LC175",
        "type": "coding",
        "category": "Database",
        "question": "【LeetCode 175】Combine Two Tables\n\nTable: Person\nTable: Address\nWrite a solution to report the first name, last name, city, and state of each person in the Person table. If the address of a personId is not present in the Address table, report null instead.\nReturn the result table in any order.\nThe result format is in the following example.\nExample 1:",
        "tags": ["Database"],
        "expected_points": ["Database"],
        "difficulty": 2,
        "code": {"language": "python", "function_signature": "", "test_cases": []},
    },
    {
        "id": "LC176",
        "type": "coding",
        "category": "Database",
        "question": "【LeetCode 176】Second Highest Salary\n\nTable: Employee\nWrite a solution to find the second highest distinct salary from the Employee table. If there is no second highest salary, return null (return None in Pandas).\nThe result format is in the following example.\nExample 1:\nExample 2:",
        "tags": ["Database"],
        "expected_points": ["Database"],
        "difficulty": 3,
        "code": {"language": "python", "function_signature": "", "test_cases": []},
    },
    {
        "id": "LC177",
        "type": "coding",
        "category": "Database",
        "question": "【LeetCode 177】Nth Highest Salary\n\nTable: Employee\nWrite a solution to find the nth highest distinct salary from the Employee table. If there are less than n distinct salaries, return null.\nThe result format is in the following example.\nExample 1:\nExample 2:",
        "tags": ["Database"],
        "expected_points": ["Database"],
        "difficulty": 3,
        "code": {"language": "python", "function_signature": "", "test_cases": []},
    },
    {
        "id": "LC178",
        "type": "coding",
        "category": "Database",
        "question": "【LeetCode 178】Rank Scores\n\nTable: Scores\nWrite a solution to find the rank of the scores. The ranking should be calculated according to the following rules:\nReturn the result table ordered by score in descending order.\nThe result format is in the following example.\nExample 1:",
        "tags": ["Database"],
        "expected_points": ["Database"],
        "difficulty": 3,
        "code": {"language": "python", "function_signature": "", "test_cases": []},
    },
    {
        "id": "LC180",
        "type": "coding",
        "category": "Database",
        "question": "【LeetCode 180】Consecutive Numbers\n\nTable: Logs\nFind all numbers that appear at least three times consecutively.\nReturn the result table in any order.\nThe result format is in the following example.\nExample 1:",
        "tags": ["Database"],
        "expected_points": ["Database"],
        "difficulty": 3,
        "code": {"language": "python", "function_signature": "", "test_cases": []},
    },
    {
        "id": "LC181",
        "type": "coding",
        "category": "Database",
        "question": "【LeetCode 181】Employees Earning More Than Their Managers\n\nTable: Employee\nWrite a solution to find the employees who earn more than their managers.\nReturn the result table in any order.\nThe result format is in the following example.\nExample 1:",
        "tags": ["Database"],
        "expected_points": ["Database"],
        "difficulty": 2,
        "code": {"language": "python", "function_signature": "", "test_cases": []},
    },
    {
        "id": "LC190",
        "type": "coding",
        "category": "Divide and Conquer",
        "question": "【LeetCode 190】Reverse Bits\n\nReverse bits of a given 32 bits unsigned integer.\nNote:\nExample 1:\nExample 2:\nConstraints:\nFollow up: If this function is called many times, how would you optimize it?",
        "tags": ["Divide and Conquer", "Bit Manipulation"],
        "expected_points": ["Divide and Conquer", "Bit Manipulation"],
        "difficulty": 2,
        "code": {"language": "python", "function_signature": "class Solution:\n    def reverseBits(self, n: int) -> int:", "test_cases": [{"name": "用例1", "input_code": "sol = Solution()\nprint(sol.reverseBits(n=43261596))", "expected": "964176192"}, {"name": "用例2", "input_code": "sol = Solution()\nprint(sol.reverseBits(n=2147483644))", "expected": "1073741822"}]},
    },
    {
        "id": "LC191",
        "type": "coding",
        "category": "Divide and Conquer",
        "question": "【LeetCode 191】Number of 1 Bits\n\nGiven a positive integer n, write a function that returns the number of set bits in its binary representation (also known as the Hamming weight).\nExample 1:\nExample 2:\nExample 3:\nConstraints:",
        "tags": ["Divide and Conquer", "Bit Manipulation"],
        "expected_points": ["Divide and Conquer", "Bit Manipulation"],
        "difficulty": 2,
        "code": {"language": "python", "function_signature": "class Solution:\n    def hammingWeight(self, n: int) -> int:", "test_cases": [{"name": "用例1", "input_code": "sol = Solution()\nprint(sol.hammingWeight(n=11))", "expected": "3"}, {"name": "用例2", "input_code": "sol = Solution()\nprint(sol.hammingWeight(n=128))", "expected": "1"}, {"name": "用例3", "input_code": "sol = Solution()\nprint(sol.hammingWeight(n=2147483645))", "expected": "30"}]},
    },
    {
        "id": "LC192",
        "type": "coding",
        "category": "Shell",
        "question": "【LeetCode 192】Word Frequency\n\nWrite a bash script to calculate the frequency of each word in a text file words.txt.\nFor simplicity sake, you may assume:\nExample:\nAssume that words.txt has the following content:\nYour script should output the following, sorted by descending frequency:\nNote:",
        "tags": ["Shell"],
        "expected_points": ["Shell"],
        "difficulty": 3,
        "code": {"language": "python", "function_signature": "", "test_cases": []},
    },
    {
        "id": "LC193",
        "type": "coding",
        "category": "Shell",
        "question": "【LeetCode 193】Valid Phone Numbers\n\nGiven a text file file.txt that contains a list of phone numbers (one per line), write a one-liner bash script to print all valid phone numbers.\nYou may assume that a valid phone number must appear in one of the following two formats: (xxx) xxx-xxxx or xxx-xxx-xxxx. (x means a digit)\nYou may also assume each line in the text file must not contain leading or trailing white spaces.\nExample:\nAssume that file.txt has the following content:\nYour script should output the following valid phone numbers:",
        "tags": ["Shell"],
        "expected_points": ["Shell"],
        "difficulty": 2,
        "code": {"language": "python", "function_signature": "", "test_cases": []},
    },
    {
        "id": "LC194",
        "type": "coding",
        "category": "Shell",
        "question": "【LeetCode 194】Transpose File\n\nGiven a text file file.txt, transpose its content.\nYou may assume that each row has the same number of columns, and each field is separated by the ' ' character.\nExample:\nIf file.txt has the following content:\nOutput the following:",
        "tags": ["Shell"],
        "expected_points": ["Shell"],
        "difficulty": 3,
        "code": {"language": "python", "function_signature": "", "test_cases": []},
    },
    {
        "id": "LC195",
        "type": "coding",
        "category": "Shell",
        "question": "【LeetCode 195】Tenth Line\n\nGiven a text file file.txt, print just the 10th line of the file.\nExample:\nAssume that file.txt has the following content:\nYour script should output the tenth line, which is:",
        "tags": ["Shell"],
        "expected_points": ["Shell"],
        "difficulty": 2,
        "code": {"language": "python", "function_signature": "", "test_cases": []},
    },
    {
        "id": "LC201",
        "type": "coding",
        "category": "Bit Manipulation",
        "question": "【LeetCode 201】Bitwise AND of Numbers Range\n\nGiven two integers left and right that represent the range [left, right], return the bitwise AND of all numbers in this range, inclusive.\nExample 1:\nExample 2:\nExample 3:\nConstraints:",
        "tags": ["Bit Manipulation"],
        "expected_points": ["Bit Manipulation"],
        "difficulty": 3,
        "code": {"language": "python", "function_signature": "class Solution:\n    def rangeBitwiseAnd(self, left: int, right: int) -> int:", "test_cases": [{"name": "用例1", "input_code": "sol = Solution()\nprint(sol.rangeBitwiseAnd(left=5, right=7))", "expected": "4"}, {"name": "用例2", "input_code": "sol = Solution()\nprint(sol.rangeBitwiseAnd(left=0, right=0))", "expected": "0"}, {"name": "用例3", "input_code": "sol = Solution()\nprint(sol.rangeBitwiseAnd(left=1, right=2147483647))", "expected": "0"}]},
    },
    {
        "id": "LC207",
        "type": "coding",
        "category": "Depth-First Search",
        "question": "【LeetCode 207】Course Schedule\n\nThere are a total of numCourses courses you have to take, labeled from 0 to numCourses - 1. You are given an array prerequisites where prerequisites[i] = [ai, bi] indicates that you must take course bi first if you want to take course ai.\nReturn true if you can finish all courses. Otherwise, return false.\nExample 1:\nExample 2:\nConstraints:",
        "tags": ["Depth-First Search", "Breadth-First Search", "Graph", "Topological Sort"],
        "expected_points": ["Depth-First Search", "Breadth-First Search", "Graph", "Topological Sort"],
        "difficulty": 3,
        "code": {"language": "python", "function_signature": "class Solution:\n    def canFinish(self, numCourses: int, prerequisites: List[List[int]]) -> bool:", "test_cases": [{"name": "用例1", "input_code": "sol = Solution()\nprint(sol.canFinish(numCourses=2, prerequisites=[[1, 0]]))", "expected": "True"}, {"name": "用例2", "input_code": "sol = Solution()\nprint(sol.canFinish(numCourses=2, prerequisites=[[1, 0], [0, 1]]))", "expected": "False"}]},
    },
    {
        "id": "LC210",
        "type": "coding",
        "category": "Depth-First Search",
        "question": "【LeetCode 210】Course Schedule II\n\nThere are a total of numCourses courses you have to take, labeled from 0 to numCourses - 1. You are given an array prerequisites where prerequisites[i] = [ai, bi] indicates that you must take course bi first if you want to take course ai.\nReturn the ordering of courses you should take to finish all courses. If there are many valid answers, return any of them. If it is impossible to finish all courses, return an empty array.\nExample 1:\nExample 2:\nExample 3:\nConstraints:",
        "tags": ["Depth-First Search", "Breadth-First Search", "Graph", "Topological Sort"],
        "expected_points": ["Depth-First Search", "Breadth-First Search", "Graph", "Topological Sort"],
        "difficulty": 3,
        "code": {"language": "python", "function_signature": "class Solution:\n    def findOrder(self, numCourses: int, prerequisites: List[List[int]]) -> List[int]:", "test_cases": [{"name": "用例1", "input_code": "sol = Solution()\nprint(sol.findOrder(numCourses=2, prerequisites=[[1, 0]]))", "expected": "[0, 1]"}, {"name": "用例2", "input_code": "sol = Solution()\nprint(sol.findOrder(numCourses=4, prerequisites=[[1, 0], [2, 0], [3, 1], [3, 2]]))", "expected": "[0, 2, 1, 3]"}, {"name": "用例3", "input_code": "sol = Solution()\nprint(sol.findOrder(numCourses=1, prerequisites=[]))", "expected": "[0]"}]},
    },
    {
        "id": "LC222",
        "type": "coding",
        "category": "Binary Search",
        "question": "【LeetCode 222】Count Complete Tree Nodes\n\nGiven the root of a complete binary tree, return the number of the nodes in the tree.\nAccording to Wikipedia, every level, except possibly the last, is completely filled in a complete binary tree, and all nodes in the last level are as far left as possible. It can have between 1 and 2h nodes inclusive at the last level h.\nDesign an algorithm that runs in less than O(n) time complexity.\nExample 1:\nExample 2:\nExample 3:\nConstraints:",
        "tags": ["Binary Search", "Bit Manipulation", "Tree", "Binary Tree"],
        "expected_points": ["Binary Search", "Bit Manipulation", "Tree", "Binary Tree"],
        "difficulty": 2,
        "code": {"language": "python", "function_signature": "# Definition for a binary tree node.\n# class TreeNode:\n#     def __init__(self, val=0, left=None, right=None):\n#         self.val = val\n#         self.left = left\n#         self.right = right\nclass Solution:\n    def countNodes(self, root: Optional[TreeNode]) -> int:", "test_cases": []},
    },
    {
        "id": "LC225",
        "type": "coding",
        "category": "Stack",
        "question": "【LeetCode 225】Implement Stack using Queues\n\nImplement a last-in-first-out (LIFO) stack using only two queues. The implemented stack should support all the functions of a normal stack (push, top, pop, and empty).\nImplement the MyStack class:\nNotes:\nExample 1:\nConstraints:\nFollow-up: Can you implement the stack using only one queue?",
        "tags": ["Stack", "Design", "Queue"],
        "expected_points": ["Stack", "Design", "Queue"],
        "difficulty": 2,
        "code": {"language": "python", "function_signature": "class MyStack:\n\n    def __init__(self):\n        \n\n    def push(self, x: int) -> None:\n        \n\n    def pop(self) -> int:\n        \n\n    def top(self) -> int:\n        \n\n    def empty(self) -> bool:\n        \n\n\n# Your MyStack object will be instantiated and called as such:\n# obj = MyStack()\n# obj.push(x)\n# param_2 = obj.pop()\n# param_3 = obj.top()\n# param_4 = obj.empty()", "test_cases": []},
    },
    {
        "id": "LC278",
        "type": "coding",
        "category": "Binary Search",
        "question": "【LeetCode 278】First Bad Version\n\nYou are a product manager and currently leading a team to develop a new product. Unfortunately, the latest version of your product fails the quality check. Since each version is developed based on the previous version, all the versions after a bad version are also bad.\nSuppose you have n versions [1, 2, ..., n] and you want to find out the first bad one, which causes all the following ones to be bad.\nYou are given an API bool isBadVersion(version) which returns whether version is bad. Implement a function to find the first bad version. You should minimize the number of calls to the API.\nExampl",
        "tags": ["Binary Search", "Interactive"],
        "expected_points": ["Binary Search", "Interactive"],
        "difficulty": 2,
        "code": {"language": "python", "function_signature": "# The isBadVersion API is already defined for you.\n# def isBadVersion(version: int) -> bool:\n\nclass Solution:\n    def firstBadVersion(self, n: int) -> int:", "test_cases": []},
    },
    {
        "id": "LC295",
        "type": "coding",
        "category": "Two Pointers",
        "question": "【LeetCode 295】Find Median from Data Stream\n\nThe median is the middle value in an ordered integer list. If the size of the list is even, there is no middle value, and the median is the mean of the two middle values.\nImplement the MedianFinder class:\nExample 1:\nConstraints:\nFollow up:",
        "tags": ["Two Pointers", "Design", "Sorting", "Heap (Priority Queue)", "Data Stream"],
        "expected_points": ["Two Pointers", "Design", "Sorting", "Heap (Priority Queue)", "Data Stream"],
        "difficulty": 4,
        "code": {"language": "python", "function_signature": "class MedianFinder:\n\n    def __init__(self):\n        \n\n    def addNum(self, num: int) -> None:\n        \n\n    def findMedian(self) -> float:\n        \n\n\n# Your MedianFinder object will be instantiated and called as such:\n# obj = MedianFinder()\n# obj.addNum(num)\n# param_2 = obj.findMedian()", "test_cases": []},
    },
    {
        "id": "LC310",
        "type": "coding",
        "category": "Depth-First Search",
        "question": "【LeetCode 310】Minimum Height Trees\n\nA tree is an undirected graph in which any two vertices are connected by exactly one path. In other words, any connected graph without simple cycles is a tree.\nGiven a tree of n nodes labelled from 0 to n - 1, and an array of n - 1 edges where edges[i] = [ai, bi] indicates that there is an undirected edge between the two nodes ai and bi in the tree, you can choose any node of the tree as the root. When you select a node x as the root, the result tree has height h. Among all possible rooted trees, those with minimum height (i.e. min(h))  are called minimum height trees (MHTs).\nReturn a list of ",
        "tags": ["Depth-First Search", "Breadth-First Search", "Graph", "Topological Sort"],
        "expected_points": ["Depth-First Search", "Breadth-First Search", "Graph", "Topological Sort"],
        "difficulty": 3,
        "code": {"language": "python", "function_signature": "class Solution:\n    def findMinHeightTrees(self, n: int, edges: List[List[int]]) -> List[int]:", "test_cases": [{"name": "用例1", "input_code": "sol = Solution()\nprint(sol.findMinHeightTrees(n=4, edges=[[1, 0], [1, 2], [1, 3]]))", "expected": "[1]"}, {"name": "用例2", "input_code": "sol = Solution()\nprint(sol.findMinHeightTrees(n=6, edges=[[3, 0], [3, 1], [3, 2], [3, 4], [5, 4]]))", "expected": "[3, 4]"}]},
    },
    {
        "id": "LC332",
        "type": "coding",
        "category": "Depth-First Search",
        "question": "【LeetCode 332】Reconstruct Itinerary\n\nYou are given a list of airline tickets where tickets[i] = [fromi, toi] represent the departure and the arrival airports of one flight. Reconstruct the itinerary in order and return it.\nAll of the tickets belong to a man who departs from \"JFK\", thus, the itinerary must begin with \"JFK\". If there are multiple valid itineraries, you should return the itinerary that has the smallest lexical order when read as a single string.\nYou may assume all tickets form at least one valid itinerary. You must use all the tickets once and only once.\nExample 1:\nExample 2:\nConstraints:",
        "tags": ["Depth-First Search", "Graph", "Eulerian Circuit"],
        "expected_points": ["Depth-First Search", "Graph", "Eulerian Circuit"],
        "difficulty": 4,
        "code": {"language": "python", "function_signature": "class Solution:\n    def findItinerary(self, tickets: List[List[str]]) -> List[str]:", "test_cases": [{"name": "用例1", "input_code": "sol = Solution()\nprint(sol.findItinerary(tickets=[['MUC', 'LHR'], ['JFK', 'MUC'], ['SFO', 'SJC'], ['LHR', 'SFO']]))", "expected": "['JFK', 'MUC', 'LHR', 'SFO', 'SJC']"}, {"name": "用例2", "input_code": "sol = Solution()\nprint(sol.findItinerary(tickets=[['JFK', 'SFO'], ['JFK', 'ATL'], ['SFO', 'ATL'], ['ATL', 'JFK'], ['ATL', 'SFO']]))", "expected": "['JFK', 'ATL', 'JFK', 'SFO', 'ATL', 'SFO']"}]},
    },
    {
        "id": "LC337",
        "type": "coding",
        "category": "Dynamic Programming",
        "question": "【LeetCode 337】House Robber III\n\nThe thief has found himself a new place for his thievery again. There is only one entrance to this area, called root.\nBesides the root, each house has one and only one parent house. After a tour, the smart thief realized that all houses in this place form a binary tree. It will automatically contact the police if two directly-linked houses were broken into on the same night.\nGiven the root of the binary tree, return the maximum amount of money the thief can rob without alerting the police.\nExample 1:\nExample 2:\nConstraints:",
        "tags": ["Dynamic Programming", "Tree", "Depth-First Search", "Binary Tree"],
        "expected_points": ["Dynamic Programming", "Tree", "Depth-First Search", "Binary Tree"],
        "difficulty": 3,
        "code": {"language": "python", "function_signature": "# Definition for a binary tree node.\n# class TreeNode:\n#     def __init__(self, val=0, left=None, right=None):\n#         self.val = val\n#         self.left = left\n#         self.right = right\nclass Solution:\n    def rob(self, root: Optional[TreeNode]) -> int:", "test_cases": []},
    },
    {
        "id": "LC338",
        "type": "coding",
        "category": "Dynamic Programming",
        "question": "【LeetCode 338】Counting Bits\n\nGiven an integer n, return an array ans of length n + 1 such that for each i (0 <= i <= n), ans[i] is the number of 1's in the binary representation of i.\nExample 1:\nExample 2:\nConstraints:\nFollow up:",
        "tags": ["Dynamic Programming", "Bit Manipulation"],
        "expected_points": ["Dynamic Programming", "Bit Manipulation"],
        "difficulty": 2,
        "code": {"language": "python", "function_signature": "class Solution:\n    def countBits(self, n: int) -> List[int]:", "test_cases": [{"name": "用例1", "input_code": "sol = Solution()\nprint(sol.countBits(n=2))", "expected": "[0, 1, 1]"}, {"name": "用例2", "input_code": "sol = Solution()\nprint(sol.countBits(n=5))", "expected": "[0, 1, 1, 2, 1, 2]"}]},
    },
    {
        "id": "LC352",
        "type": "coding",
        "category": "Binary Search",
        "question": "【LeetCode 352】Data Stream as Disjoint Intervals\n\nGiven a data stream input of non-negative integers a1, a2, ..., an, summarize the numbers seen so far as a list of disjoint intervals.\nImplement the SummaryRanges class:\nExample 1:\nConstraints:\nFollow up: What if there are lots of merges and the number of disjoint intervals is small compared to the size of the data stream?",
        "tags": ["Binary Search", "Design", "Ordered Set"],
        "expected_points": ["Binary Search", "Design", "Ordered Set"],
        "difficulty": 4,
        "code": {"language": "python", "function_signature": "class SummaryRanges:\n\n    def __init__(self):\n        \n\n    def addNum(self, value: int) -> None:\n        \n\n    def getIntervals(self) -> List[List[int]]:\n        \n\n\n# Your SummaryRanges object will be instantiated and called as such:\n# obj = SummaryRanges()\n# obj.addNum(value)\n# param_2 = obj.getIntervals()", "test_cases": []},
    },
    {
        "id": "LC374",
        "type": "coding",
        "category": "Binary Search",
        "question": "【LeetCode 374】Guess Number Higher or Lower\n\nWe are playing the Guess Game. The game is as follows:\nI pick a number from 1 to n. You have to guess which number I picked.\nEvery time you guess wrong, I will tell you whether the number I picked is higher or lower than your guess.\nYou call a pre-defined API int guess(int num), which returns three possible results:\nReturn the number that I picked.\nExample 1:\nExample 2:\nExample 3:\nConstraints:",
        "tags": ["Binary Search", "Interactive"],
        "expected_points": ["Binary Search", "Interactive"],
        "difficulty": 2,
        "code": {"language": "python", "function_signature": "# The guess API is already defined for you.\n# @param num, your guess\n# @return -1 if num is higher than the picked number\n#          1 if num is lower than the picked number\n#          otherwise return 0\n# def guess(num: int) -> int:\n\nclass Solution:\n    def guessNumber(self, n: int) -> int:", "test_cases": []},
    },
    {
        "id": "LC386",
        "type": "coding",
        "category": "Depth-First Search",
        "question": "【LeetCode 386】Lexicographical Numbers\n\nGiven an integer n, return all the numbers in the range [1, n] sorted in lexicographical order.\nYou must write an algorithm that runs in O(n) time and uses O(1) extra space.\nExample 1:\nExample 2:\nConstraints:",
        "tags": ["Depth-First Search", "Trie"],
        "expected_points": ["Depth-First Search", "Trie"],
        "difficulty": 3,
        "code": {"language": "python", "function_signature": "class Solution:\n    def lexicalOrder(self, n: int) -> List[int]:", "test_cases": [{"name": "用例1", "input_code": "sol = Solution()\nprint(sol.lexicalOrder(n=13))", "expected": "[1, 10, 11, 12, 13, 2, 3, 4, 5, 6, 7, 8, 9]"}, {"name": "用例2", "input_code": "sol = Solution()\nprint(sol.lexicalOrder(n=2))", "expected": "[1, 2]"}]},
    },
    {
        "id": "LC397",
        "type": "coding",
        "category": "Dynamic Programming",
        "question": "【LeetCode 397】Integer Replacement\n\nGiven a positive integer n, you can apply one of the following operations:\nReturn the minimum number of operations needed for n to become 1.\nExample 1:\nExample 2:\nExample 3:\nConstraints:",
        "tags": ["Dynamic Programming", "Greedy", "Bit Manipulation", "Memoization"],
        "expected_points": ["Dynamic Programming", "Greedy", "Bit Manipulation", "Memoization"],
        "difficulty": 3,
        "code": {"language": "python", "function_signature": "class Solution:\n    def integerReplacement(self, n: int) -> int:", "test_cases": [{"name": "用例1", "input_code": "sol = Solution()\nprint(sol.integerReplacement(n=8))", "expected": "3"}, {"name": "用例2", "input_code": "sol = Solution()\nprint(sol.integerReplacement(n=7))", "expected": "4"}, {"name": "用例3", "input_code": "sol = Solution()\nprint(sol.integerReplacement(n=4))", "expected": "2"}]},
    },
    {
        "id": "LC401",
        "type": "coding",
        "category": "Backtracking",
        "question": "【LeetCode 401】Binary Watch\n\nA binary watch has 4 LEDs on the top to represent the hours (0-11), and 6 LEDs on the bottom to represent the minutes (0-59). Each LED represents a zero or one, with the least significant bit on the right.\nGiven an integer turnedOn which represents the number of LEDs that are currently on (ignoring the PM), return all possible times the watch could represent. You may return the answer in any order.\nThe hour must not contain a leading zero.\nThe minute must consist of two digits and may contain a leading zero.\nExample 1:\nExample 2:\nConstraints:",
        "tags": ["Backtracking", "Bit Manipulation"],
        "expected_points": ["Backtracking", "Bit Manipulation"],
        "difficulty": 2,
        "code": {"language": "python", "function_signature": "class Solution:\n    def readBinaryWatch(self, turnedOn: int) -> List[str]:", "test_cases": [{"name": "用例1", "input_code": "sol = Solution()\nprint(sol.readBinaryWatch(turnedOn=1))", "expected": "['0:01', '0:02', '0:04', '0:08', '0:16', '0:32', '1:00', '2:00', '4:00', '8:00']"}, {"name": "用例2", "input_code": "sol = Solution()\nprint(sol.readBinaryWatch(turnedOn=9))", "expected": "[]"}]},
    },
    {
        "id": "LC440",
        "type": "coding",
        "category": "Trie",
        "question": "【LeetCode 440】K-th Smallest in Lexicographical Order\n\nGiven two integers n and k, return the kth lexicographically smallest integer in the range [1, n].\nExample 1:\nExample 2:\nConstraints:",
        "tags": ["Trie"],
        "expected_points": ["Trie"],
        "difficulty": 4,
        "code": {"language": "python", "function_signature": "class Solution:\n    def findKthNumber(self, n: int, k: int) -> int:", "test_cases": [{"name": "用例1", "input_code": "sol = Solution()\nprint(sol.findKthNumber(n=13, k=2))", "expected": "10"}, {"name": "用例2", "input_code": "sol = Solution()\nprint(sol.findKthNumber(n=1, k=1))", "expected": "1"}]},
    },
    {
        "id": "LC461",
        "type": "coding",
        "category": "Bit Manipulation",
        "question": "【LeetCode 461】Hamming Distance\n\nThe Hamming distance between two integers is the number of positions at which the corresponding bits are different.\nGiven two integers x and y, return the Hamming distance between them.\nExample 1:\nExample 2:\nConstraints:\nNote: This question is the same as  2220: Minimum Bit Flips to Convert Number.",
        "tags": ["Bit Manipulation"],
        "expected_points": ["Bit Manipulation"],
        "difficulty": 2,
        "code": {"language": "python", "function_signature": "class Solution:\n    def hammingDistance(self, x: int, y: int) -> int:", "test_cases": [{"name": "用例1", "input_code": "sol = Solution()\nprint(sol.hammingDistance(x=1, y=4))", "expected": "2"}, {"name": "用例2", "input_code": "sol = Solution()\nprint(sol.hammingDistance(x=3, y=1))", "expected": "1"}]},
    },
    {
        "id": "LC476",
        "type": "coding",
        "category": "Bit Manipulation",
        "question": "【LeetCode 476】Number Complement\n\nThe complement of an integer is the integer you get when you flip all the 0's to 1's and all the 1's to 0's in its binary representation.\nGiven an integer num, return its complement.\nExample 1:\nExample 2:\nConstraints:\nNote: This question is the same as 1009: https://leetcode.com/problems/complement-of-base-10-integer/",
        "tags": ["Bit Manipulation"],
        "expected_points": ["Bit Manipulation"],
        "difficulty": 2,
        "code": {"language": "python", "function_signature": "class Solution:\n    def findComplement(self, num: int) -> int:", "test_cases": [{"name": "用例1", "input_code": "sol = Solution()\nprint(sol.findComplement(num=5))", "expected": "2"}, {"name": "用例2", "input_code": "sol = Solution()\nprint(sol.findComplement(num=1))", "expected": "0"}]},
    },
    {
        "id": "LC547",
        "type": "coding",
        "category": "Depth-First Search",
        "question": "【LeetCode 547】Number of Provinces\n\nThere are n cities. Some of them are connected, while some are not. If city a is connected directly with city b, and city b is connected directly with city c, then city a is connected indirectly with city c.\nA province is a group of directly or indirectly connected cities and no other cities outside of the group.\nYou are given an n x n matrix isConnected where isConnected[i][j] = 1 if the ith city and the jth city are directly connected, and isConnected[i][j] = 0 otherwise.\nReturn the total number of provinces.\nExample 1:\nExample 2:\nConstraints:",
        "tags": ["Depth-First Search", "Breadth-First Search", "Union Find", "Graph"],
        "expected_points": ["Depth-First Search", "Breadth-First Search", "Union Find", "Graph"],
        "difficulty": 3,
        "code": {"language": "python", "function_signature": "class Solution:\n    def findCircleNum(self, isConnected: List[List[int]]) -> int:", "test_cases": [{"name": "用例1", "input_code": "sol = Solution()\nprint(sol.findCircleNum(isConnected=[[1, 1, 0], [1, 1, 0], [0, 0, 1]]))", "expected": "2"}, {"name": "用例2", "input_code": "sol = Solution()\nprint(sol.findCircleNum(isConnected=[[1, 0, 0], [0, 1, 0], [0, 0, 1]]))", "expected": "3"}]},
    },
    {
        "id": "LC552",
        "type": "coding",
        "category": "Dynamic Programming",
        "question": "【LeetCode 552】Student Attendance Record II\n\nAn attendance record for a student can be represented as a string where each character signifies whether the student was absent, late, or present on that day. The record only contains the following three characters:\nAny student is eligible for an attendance award if they meet both of the following criteria:\nGiven an integer n, return the number of possible attendance records of length n that make a student eligible for an attendance award. The answer may be very large, so return it modulo 109 + 7.\nExample 1:\nExample 2:\nExample 3:\nConstraints:",
        "tags": ["Dynamic Programming"],
        "expected_points": ["Dynamic Programming"],
        "difficulty": 4,
        "code": {"language": "python", "function_signature": "class Solution:\n    def checkRecord(self, n: int) -> int:", "test_cases": [{"name": "用例1", "input_code": "sol = Solution()\nprint(sol.checkRecord(n=2))", "expected": "8"}, {"name": "用例2", "input_code": "sol = Solution()\nprint(sol.checkRecord(n=1))", "expected": "3"}, {"name": "用例3", "input_code": "sol = Solution()\nprint(sol.checkRecord(n=10101))", "expected": "183236316"}]},
    },
    {
        "id": "LC558",
        "type": "coding",
        "category": "Divide and Conquer",
        "question": "【LeetCode 558】Logical OR of Two Binary Grids Represented as Quad-Trees\n\nA Binary Matrix is a matrix in which all the elements are either 0 or 1.\nGiven quadTree1 and quadTree2. quadTree1 represents a n * n binary matrix and quadTree2 represents another n * n binary matrix.\nReturn a Quad-Tree representing the n * n binary matrix which is the result of logical bitwise OR of the two binary matrixes represented by quadTree1 and quadTree2.\nNotice that you can assign the value of a node to True or False when isLeaf is False, and both are accepted in the answer.\nA Quad-Tree is a tree data structure in which each internal node has exactly four children. Besides, each node ",
        "tags": ["Divide and Conquer", "Tree"],
        "expected_points": ["Divide and Conquer", "Tree"],
        "difficulty": 3,
        "code": {"language": "python", "function_signature": "\"\"\"\n# Definition for a QuadTree node.\nclass Node:\n    def __init__(self, val, isLeaf, topLeft, topRight, bottomLeft, bottomRight):\n        self.val = val\n        self.isLeaf = isLeaf\n        self.topLeft = topLeft\n        self.topRight = topRight\n        self.bottomLeft = bottomLeft\n        self.bottomRight = bottomRight\n\"\"\"\n\nclass Solution:\n    def intersect(self, quadTree1: 'Node', quadTree2: 'Node') -> 'Node':", "test_cases": []},
    },
    {
        "id": "LC693",
        "type": "coding",
        "category": "Bit Manipulation",
        "question": "【LeetCode 693】Binary Number with Alternating Bits\n\nGiven a positive integer, check whether it has alternating bits: namely, if two adjacent bits will always have different values.\nExample 1:\nExample 2:\nExample 3:\nConstraints:",
        "tags": ["Bit Manipulation"],
        "expected_points": ["Bit Manipulation"],
        "difficulty": 2,
        "code": {"language": "python", "function_signature": "class Solution:\n    def hasAlternatingBits(self, n: int) -> bool:", "test_cases": [{"name": "用例1", "input_code": "sol = Solution()\nprint(sol.hasAlternatingBits(n=5))", "expected": "True"}, {"name": "用例2", "input_code": "sol = Solution()\nprint(sol.hasAlternatingBits(n=7))", "expected": "False"}, {"name": "用例3", "input_code": "sol = Solution()\nprint(sol.hasAlternatingBits(n=11))", "expected": "False"}]},
    },
    {
        "id": "LC756",
        "type": "coding",
        "category": "Bit Manipulation",
        "question": "【LeetCode 756】Pyramid Transition Matrix\n\nYou are stacking blocks to form a pyramid. Each block has a color, which is represented by a single letter. Each row of blocks contains one less block than the row beneath it and is centered on top.\nTo make the pyramid aesthetically pleasing, there are only specific triangular patterns that are allowed. A triangular pattern consists of a single block stacked on top of two blocks. The patterns are given as a list of three-letter strings allowed, where the first two characters of a pattern represent the left and right bottom blocks respectively, and the third character is the top block.\nYou star",
        "tags": ["Bit Manipulation", "Depth-First Search", "Breadth-First Search"],
        "expected_points": ["Bit Manipulation", "Depth-First Search", "Breadth-First Search"],
        "difficulty": 3,
        "code": {"language": "python", "function_signature": "class Solution:\n    def pyramidTransition(self, bottom: str, allowed: List[str]) -> bool:", "test_cases": [{"name": "用例1", "input_code": "sol = Solution()\nprint(sol.pyramidTransition(bottom='BCD', allowed=['BCC', 'CDE', 'CEA', 'FFF']))", "expected": "True"}, {"name": "用例2", "input_code": "sol = Solution()\nprint(sol.pyramidTransition(bottom='AAAA', allowed=['AAB', 'AAC', 'BCD', 'BBE', 'DEF']))", "expected": "False"}]},
    },
    {
        "id": "LC797",
        "type": "coding",
        "category": "Backtracking",
        "question": "【LeetCode 797】All Paths From Source to Target\n\nGiven a directed acyclic graph (DAG) of n nodes labeled from 0 to n - 1, find all possible paths from node 0 to node n - 1 and return them in any order.\nThe graph is given as follows: graph[i] is a list of all nodes you can visit from node i (i.e., there is a directed edge from node i to node graph[i][j]).\nExample 1:\nExample 2:\nConstraints:",
        "tags": ["Backtracking", "Depth-First Search", "Breadth-First Search", "Graph"],
        "expected_points": ["Backtracking", "Depth-First Search", "Breadth-First Search", "Graph"],
        "difficulty": 3,
        "code": {"language": "python", "function_signature": "class Solution:\n    def allPathsSourceTarget(self, graph: List[List[int]]) -> List[List[int]]:", "test_cases": [{"name": "用例1", "input_code": "sol = Solution()\nprint(sol.allPathsSourceTarget(graph=[[1, 2], [3], [3], []]))", "expected": "[[0, 1, 3], [0, 2, 3]]"}, {"name": "用例2", "input_code": "sol = Solution()\nprint(sol.allPathsSourceTarget(graph=[[4, 3, 1], [3, 2, 4], [3], [4], []]))", "expected": "[[0, 4], [0, 3, 4], [0, 1, 3, 4], [0, 1, 2, 3, 4], [0, 1, 4]]"}]},
    },
    {
        "id": "LC868",
        "type": "coding",
        "category": "Bit Manipulation",
        "question": "【LeetCode 868】Binary Gap\n\nGiven a positive integer n, find and return the longest distance between any two adjacent 1's in the binary representation of n. If there are no two adjacent 1's, return 0.\nTwo 1's are adjacent if there are only 0's separating them (possibly no 0's). The distance between two 1's is the absolute difference between their bit positions. For example, the two 1's in \"1001\" have a distance of 3.\nExample 1:\nExample 2:\nExample 3:\nConstraints:",
        "tags": ["Bit Manipulation"],
        "expected_points": ["Bit Manipulation"],
        "difficulty": 2,
        "code": {"language": "python", "function_signature": "class Solution:\n    def binaryGap(self, n: int) -> int:", "test_cases": [{"name": "用例1", "input_code": "sol = Solution()\nprint(sol.binaryGap(n=22))", "expected": "2"}, {"name": "用例2", "input_code": "sol = Solution()\nprint(sol.binaryGap(n=8))", "expected": "0"}, {"name": "用例3", "input_code": "sol = Solution()\nprint(sol.binaryGap(n=5))", "expected": "2"}]},
    },
    {
        "id": "LC933",
        "type": "coding",
        "category": "Design",
        "question": "【LeetCode 933】Number of Recent Calls\n\nYou have a RecentCounter class which counts the number of recent requests within a certain time frame.\nImplement the RecentCounter class:\nIt is guaranteed that every call to ping uses a strictly larger value of t than the previous call.\nExample 1:\nConstraints:",
        "tags": ["Design", "Queue", "Data Stream"],
        "expected_points": ["Design", "Queue", "Data Stream"],
        "difficulty": 2,
        "code": {"language": "python", "function_signature": "class RecentCounter:\n\n    def __init__(self):\n        \n\n    def ping(self, t: int) -> int:\n        \n\n\n# Your RecentCounter object will be instantiated and called as such:\n# obj = RecentCounter()\n# param_1 = obj.ping(t)", "test_cases": []},
    },
    {
        "id": "LC1114",
        "type": "coding",
        "category": "Concurrency",
        "question": "【LeetCode 1114】Print in Order\n\nSuppose we have a class:\nThe same instance of Foo will be passed to three different threads. Thread A will call first(), thread B will call second(), and thread C will call third(). Design a mechanism and modify the program to ensure that second() is executed after first(), and third() is executed after second().\nNote:\nWe do not know how the threads will be scheduled in the operating system, even though the numbers in the input seem to imply the ordering. The input format you see is mainly to ensure our tests' comprehensiveness.\nExample 1:\nExample 2:\nConstraints:",
        "tags": ["Concurrency"],
        "expected_points": ["Concurrency"],
        "difficulty": 2,
        "code": {"language": "python", "function_signature": "class Foo:\n    def __init__(self):\n        pass\n\n\n    def first(self, printFirst: 'Callable[[], None]') -> None:\n        \n        # printFirst() outputs \"first\". Do not change or remove this line.\n        printFirst()\n\n\n    def second(self, printSecond: 'Callable[[], None]') -> None:\n        \n        # printSecond() outputs \"second\". Do not change or remove this line.\n        printSecond()\n\n\n    def third(self, printThird: 'Callable[[], None]') -> None:\n        \n        # printThird() outputs \"third\". Do not change or remove this line.\n        printThird()", "test_cases": []},
    },
    {
        "id": "LC1603",
        "type": "coding",
        "category": "Design",
        "question": "【LeetCode 1603】Design Parking System\n\nDesign a parking system for a parking lot. The parking lot has three kinds of parking spaces: big, medium, and small, with a fixed number of slots for each size.\nImplement the ParkingSystem class:\nExample 1:\nConstraints:",
        "tags": ["Design", "Simulation", "Counting"],
        "expected_points": ["Design", "Simulation", "Counting"],
        "difficulty": 2,
        "code": {"language": "python", "function_signature": "class ParkingSystem:\n\n    def __init__(self, big: int, medium: int, small: int):\n        \n\n    def addCar(self, carType: int) -> bool:\n        \n\n\n# Your ParkingSystem object will be instantiated and called as such:\n# obj = ParkingSystem(big, medium, small)\n# param_1 = obj.addCar(carType)", "test_cases": []},
    },
    {
        "id": "LC1791",
        "type": "coding",
        "category": "Graph",
        "question": "【LeetCode 1791】Find Center of Star Graph\n\nThere is an undirected star graph consisting of n nodes labeled from 1 to n. A star graph is a graph where there is one center node and exactly n - 1 edges that connect the center node with every other node.\nYou are given a 2D integer array edges where each edges[i] = [ui, vi] indicates that there is an edge between the nodes ui and vi. Return the center of the given star graph.\nExample 1:\nExample 2:\nConstraints:",
        "tags": ["Graph"],
        "expected_points": ["Graph"],
        "difficulty": 2,
        "code": {"language": "python", "function_signature": "class Solution:\n    def findCenter(self, edges: List[List[int]]) -> int:", "test_cases": [{"name": "用例1", "input_code": "sol = Solution()\nprint(sol.findCenter(edges=[[1, 2], [2, 3], [4, 2]]))", "expected": "2"}, {"name": "用例2", "input_code": "sol = Solution()\nprint(sol.findCenter(edges=[[1, 2], [5, 1], [1, 3], [1, 4]]))", "expected": "1"}]},
    },
    {
        "id": "LC2231",
        "type": "coding",
        "category": "Sorting",
        "question": "【LeetCode 2231】Largest Number After Digit Swaps by Parity\n\nYou are given a positive integer num. You may swap any two digits of num that have the same parity (i.e. both odd digits or both even digits).\nReturn the largest possible value of num after any number of swaps.\nExample 1:\nExample 2:\nConstraints:",
        "tags": ["Sorting", "Heap (Priority Queue)"],
        "expected_points": ["Sorting", "Heap (Priority Queue)"],
        "difficulty": 2,
        "code": {"language": "python", "function_signature": "class Solution:\n    def largestInteger(self, num: int) -> int:", "test_cases": [{"name": "用例1", "input_code": "sol = Solution()\nprint(sol.largestInteger(num=1234))", "expected": "3412"}, {"name": "用例2", "input_code": "sol = Solution()\nprint(sol.largestInteger(num=65875))", "expected": "87655"}]},
    },
    {
        "id": "LC2619",
        "type": "coding",
        "category": "LeetCode",
        "question": "【LeetCode 2619】Array Prototype Last\n\nWrite code that enhances all arrays such that you can call the array.last() method on any array and it will return the last element. If there are no elements in the array, it should return -1.\nYou may assume the array is the output of JSON.parse.\nExample 1:\nExample 2:\nConstraints:",
        "tags": [],
        "expected_points": [],
        "difficulty": 2,
        "code": {"language": "python", "function_signature": "", "test_cases": []},
    },
    {
        "id": "LC2620",
        "type": "coding",
        "category": "LeetCode",
        "question": "【LeetCode 2620】Counter\n\nGiven an integer n, return a counter function. This counter function initially returns n and then returns 1 more than the previous value every subsequent time it is called (n, n + 1, n + 2, etc).\nExample 1:\nExample 2:\nConstraints:",
        "tags": [],
        "expected_points": [],
        "difficulty": 2,
        "code": {"language": "python", "function_signature": "", "test_cases": []},
    },
    {
        "id": "LC2621",
        "type": "coding",
        "category": "LeetCode",
        "question": "【LeetCode 2621】Sleep\n\nGiven a positive integer millis, write an asynchronous function that sleeps for millis milliseconds. It can resolve any value.\nNote that minor deviation from millis in the actual sleep duration is acceptable.\nExample 1:\nExample 2:\nConstraints:",
        "tags": [],
        "expected_points": [],
        "difficulty": 2,
        "code": {"language": "python", "function_signature": "", "test_cases": []},
    },
    {
        "id": "LC2626",
        "type": "coding",
        "category": "LeetCode",
        "question": "【LeetCode 2626】Array Reduce Transformation\n\nGiven an integer array nums, a reducer function fn, and an initial value init, return the final result obtained by executing the fn function on each element of the array, sequentially, passing in the return value from the calculation on the preceding element.\nThis result is achieved through the following operations: val = fn(init, nums[0]), val = fn(val, nums[1]), val = fn(val, nums[2]), ... until every element in the array has been processed. The ultimate value of val is then returned.\nIf the length of the array is 0, the function should return init.\nPlease solve it without using the built-in",
        "tags": [],
        "expected_points": [],
        "difficulty": 2,
        "code": {"language": "python", "function_signature": "", "test_cases": []},
    },
    {
        "id": "LC2629",
        "type": "coding",
        "category": "LeetCode",
        "question": "【LeetCode 2629】Function Composition\n\nGiven an array of functions [f1, f2, f3, ..., fn], return a new function fn that is the function composition of the array of functions.\nThe function composition of [f(x), g(x), h(x)] is fn(x) = f(g(h(x))).\nThe function composition of an empty list of functions is the identity function f(x) = x.\nYou may assume each function in the array accepts one integer as input and returns one integer as output.\nExample 1:\nExample 2:\nExample 3:\nConstraints:",
        "tags": [],
        "expected_points": [],
        "difficulty": 2,
        "code": {"language": "python", "function_signature": "", "test_cases": []},
    },
    {
        "id": "LC2634",
        "type": "coding",
        "category": "LeetCode",
        "question": "【LeetCode 2634】Filter Elements from Array\n\nGiven an integer array arr and a filtering function fn, return a filtered array filteredArr.\nThe fn function takes one or two arguments:\nfilteredArr should only contain the elements from the arr for which the expression fn(arr[i], i) evaluates to a truthy value. A truthy value is a value where Boolean(value) returns true.\nPlease solve it without the built-in Array.filter method.\nExample 1:\nExample 2:\nExample 3:\nConstraints:",
        "tags": [],
        "expected_points": [],
        "difficulty": 2,
        "code": {"language": "python", "function_signature": "", "test_cases": []},
    },
]
